services:
  # A web service for our frontend, served by Nginx
  - type: web
    name: frontend
    runtime: docker
    dockerfilePath: ./Dockerfile.frontend
    # Nginx will handle routing and serving static files
    # The proxy to the backend is configured in nginx.conf
    # The frontend is exposed on port 80 of the container
    # and Render will map it to a public URL

  # A private service for our backend
  - type: web
    name: backend
    runtime: docker
    dockerfilePath: ./Dockerfile.backend
    # The port is not exposed to the public internet
    # It is only accessible from the frontend
    # through the rewrite rule above
    envVars:
      - key: PORT
        value: 5001
      - key: PYTHON_VERSION
        value: 3.9.13

  # A cron job to run our daily processing
  - type: cron
    name: daily-processing
    schedule: "0 11 * * *"
    runtime: docker
    dockerfilePath: ./Dockerfile.backend
    dockerCommand: "python /app/main.py -accumulate_scores -output_file output/accumulated.xlsx && python /app/main.py -vgmscore_filter A -output_file output/vgm_filtered_A.xlsx && python /app/main.py -vgmscore_filter A,B -output_file output/vgm_filtered_AB.xlsx" 